// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/LoadTest.proto

package org.apache.hedwig.protocol;

public final class LoadTest {
  private LoadTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoadTestMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 timestamp = 1;
    boolean hasTimestamp();
    long getTimestamp();
    
    // required bytes body = 2;
    boolean hasBody();
    com.google.protobuf.ByteString getBody();
  }
  public static final class LoadTestMessage extends
      com.google.protobuf.GeneratedMessage
      implements LoadTestMessageOrBuilder {
    // Use LoadTestMessage.newBuilder() to construct.
    private LoadTestMessage(Builder builder) {
      super(builder);
    }
    private LoadTestMessage(boolean noInit) {}
    
    private static final LoadTestMessage defaultInstance;
    public static LoadTestMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoadTestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hedwig.protocol.LoadTest.internal_static_LoadTestMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hedwig.protocol.LoadTest.internal_static_LoadTestMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // required bytes body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    
    private void initFields() {
      timestamp_ = 0L;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, body_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.hedwig.protocol.LoadTest.LoadTestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.LoadTestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.LoadTestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.LoadTestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.LoadTestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.LoadTestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.LoadTestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hedwig.protocol.LoadTest.LoadTestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hedwig.protocol.LoadTest.LoadTestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.LoadTestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.hedwig.protocol.LoadTest.LoadTestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.hedwig.protocol.LoadTest.LoadTestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.hedwig.protocol.LoadTest.internal_static_LoadTestMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.hedwig.protocol.LoadTest.internal_static_LoadTestMessage_fieldAccessorTable;
      }
      
      // Construct using org.apache.hedwig.protocol.LoadTest.LoadTestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.hedwig.protocol.LoadTest.LoadTestMessage.getDescriptor();
      }
      
      public org.apache.hedwig.protocol.LoadTest.LoadTestMessage getDefaultInstanceForType() {
        return org.apache.hedwig.protocol.LoadTest.LoadTestMessage.getDefaultInstance();
      }
      
      public org.apache.hedwig.protocol.LoadTest.LoadTestMessage build() {
        org.apache.hedwig.protocol.LoadTest.LoadTestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.hedwig.protocol.LoadTest.LoadTestMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.hedwig.protocol.LoadTest.LoadTestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.hedwig.protocol.LoadTest.LoadTestMessage buildPartial() {
        org.apache.hedwig.protocol.LoadTest.LoadTestMessage result = new org.apache.hedwig.protocol.LoadTest.LoadTestMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.hedwig.protocol.LoadTest.LoadTestMessage) {
          return mergeFrom((org.apache.hedwig.protocol.LoadTest.LoadTestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.hedwig.protocol.LoadTest.LoadTestMessage other) {
        if (other == org.apache.hedwig.protocol.LoadTest.LoadTestMessage.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasBody()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              body_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 timestamp = 1;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required bytes body = 2;
      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:LoadTestMessage)
    }
    
    static {
      defaultInstance = new LoadTestMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LoadTestMessage)
  }
  
  public interface MessageProviderValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes topic = 1;
    boolean hasTopic();
    com.google.protobuf.ByteString getTopic();
    
    // required .LoadTestMessage message = 2;
    boolean hasMessage();
    org.apache.hedwig.protocol.LoadTest.LoadTestMessage getMessage();
    org.apache.hedwig.protocol.LoadTest.LoadTestMessageOrBuilder getMessageOrBuilder();
  }
  public static final class MessageProviderValue extends
      com.google.protobuf.GeneratedMessage
      implements MessageProviderValueOrBuilder {
    // Use MessageProviderValue.newBuilder() to construct.
    private MessageProviderValue(Builder builder) {
      super(builder);
    }
    private MessageProviderValue(boolean noInit) {}
    
    private static final MessageProviderValue defaultInstance;
    public static MessageProviderValue getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageProviderValue getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hedwig.protocol.LoadTest.internal_static_MessageProviderValue_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hedwig.protocol.LoadTest.internal_static_MessageProviderValue_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes topic = 1;
    public static final int TOPIC_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString topic_;
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getTopic() {
      return topic_;
    }
    
    // required .LoadTestMessage message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private org.apache.hedwig.protocol.LoadTest.LoadTestMessage message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.apache.hedwig.protocol.LoadTest.LoadTestMessage getMessage() {
      return message_;
    }
    public org.apache.hedwig.protocol.LoadTest.LoadTestMessageOrBuilder getMessageOrBuilder() {
      return message_;
    }
    
    private void initFields() {
      topic_ = com.google.protobuf.ByteString.EMPTY;
      message_ = org.apache.hedwig.protocol.LoadTest.LoadTestMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTopic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMessage().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, topic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, message_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, topic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.hedwig.protocol.LoadTest.MessageProviderValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.MessageProviderValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.MessageProviderValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.MessageProviderValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.MessageProviderValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.MessageProviderValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.MessageProviderValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hedwig.protocol.LoadTest.MessageProviderValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hedwig.protocol.LoadTest.MessageProviderValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hedwig.protocol.LoadTest.MessageProviderValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.hedwig.protocol.LoadTest.MessageProviderValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.hedwig.protocol.LoadTest.MessageProviderValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.hedwig.protocol.LoadTest.internal_static_MessageProviderValue_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.hedwig.protocol.LoadTest.internal_static_MessageProviderValue_fieldAccessorTable;
      }
      
      // Construct using org.apache.hedwig.protocol.LoadTest.MessageProviderValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        topic_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (messageBuilder_ == null) {
          message_ = org.apache.hedwig.protocol.LoadTest.LoadTestMessage.getDefaultInstance();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.hedwig.protocol.LoadTest.MessageProviderValue.getDescriptor();
      }
      
      public org.apache.hedwig.protocol.LoadTest.MessageProviderValue getDefaultInstanceForType() {
        return org.apache.hedwig.protocol.LoadTest.MessageProviderValue.getDefaultInstance();
      }
      
      public org.apache.hedwig.protocol.LoadTest.MessageProviderValue build() {
        org.apache.hedwig.protocol.LoadTest.MessageProviderValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.hedwig.protocol.LoadTest.MessageProviderValue buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.hedwig.protocol.LoadTest.MessageProviderValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.hedwig.protocol.LoadTest.MessageProviderValue buildPartial() {
        org.apache.hedwig.protocol.LoadTest.MessageProviderValue result = new org.apache.hedwig.protocol.LoadTest.MessageProviderValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.topic_ = topic_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (messageBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.hedwig.protocol.LoadTest.MessageProviderValue) {
          return mergeFrom((org.apache.hedwig.protocol.LoadTest.MessageProviderValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.hedwig.protocol.LoadTest.MessageProviderValue other) {
        if (other == org.apache.hedwig.protocol.LoadTest.MessageProviderValue.getDefaultInstance()) return this;
        if (other.hasTopic()) {
          setTopic(other.getTopic());
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTopic()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        if (!getMessage().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              topic_ = input.readBytes();
              break;
            }
            case 18: {
              org.apache.hedwig.protocol.LoadTest.LoadTestMessage.Builder subBuilder = org.apache.hedwig.protocol.LoadTest.LoadTestMessage.newBuilder();
              if (hasMessage()) {
                subBuilder.mergeFrom(getMessage());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMessage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes topic = 1;
      private com.google.protobuf.ByteString topic_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getTopic() {
        return topic_;
      }
      public Builder setTopic(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      
      // required .LoadTestMessage message = 2;
      private org.apache.hedwig.protocol.LoadTest.LoadTestMessage message_ = org.apache.hedwig.protocol.LoadTest.LoadTestMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.hedwig.protocol.LoadTest.LoadTestMessage, org.apache.hedwig.protocol.LoadTest.LoadTestMessage.Builder, org.apache.hedwig.protocol.LoadTest.LoadTestMessageOrBuilder> messageBuilder_;
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.apache.hedwig.protocol.LoadTest.LoadTestMessage getMessage() {
        if (messageBuilder_ == null) {
          return message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      public Builder setMessage(org.apache.hedwig.protocol.LoadTest.LoadTestMessage value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setMessage(
          org.apache.hedwig.protocol.LoadTest.LoadTestMessage.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeMessage(org.apache.hedwig.protocol.LoadTest.LoadTestMessage value) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              message_ != org.apache.hedwig.protocol.LoadTest.LoadTestMessage.getDefaultInstance()) {
            message_ =
              org.apache.hedwig.protocol.LoadTest.LoadTestMessage.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = org.apache.hedwig.protocol.LoadTest.LoadTestMessage.getDefaultInstance();
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public org.apache.hedwig.protocol.LoadTest.LoadTestMessage.Builder getMessageBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      public org.apache.hedwig.protocol.LoadTest.LoadTestMessageOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.hedwig.protocol.LoadTest.LoadTestMessage, org.apache.hedwig.protocol.LoadTest.LoadTestMessage.Builder, org.apache.hedwig.protocol.LoadTest.LoadTestMessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.apache.hedwig.protocol.LoadTest.LoadTestMessage, org.apache.hedwig.protocol.LoadTest.LoadTestMessage.Builder, org.apache.hedwig.protocol.LoadTest.LoadTestMessageOrBuilder>(
                  message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:MessageProviderValue)
    }
    
    static {
      defaultInstance = new MessageProviderValue(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MessageProviderValue)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LoadTestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoadTestMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageProviderValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageProviderValue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/protobuf/LoadTest.proto\"2\n\017Lo" +
      "adTestMessage\022\021\n\ttimestamp\030\001 \002(\004\022\014\n\004body" +
      "\030\002 \002(\014\"H\n\024MessageProviderValue\022\r\n\005topic\030" +
      "\001 \002(\014\022!\n\007message\030\002 \002(\0132\020.LoadTestMessage" +
      "B\036\n\032org.apache.hedwig.protocolH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LoadTestMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LoadTestMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LoadTestMessage_descriptor,
              new java.lang.String[] { "Timestamp", "Body", },
              org.apache.hedwig.protocol.LoadTest.LoadTestMessage.class,
              org.apache.hedwig.protocol.LoadTest.LoadTestMessage.Builder.class);
          internal_static_MessageProviderValue_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MessageProviderValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MessageProviderValue_descriptor,
              new java.lang.String[] { "Topic", "Message", },
              org.apache.hedwig.protocol.LoadTest.MessageProviderValue.class,
              org.apache.hedwig.protocol.LoadTest.MessageProviderValue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
